.TH "FCOEMON" "8" "December 22, 2008" "Open-FCoE Applications" "Open-FCoE Tools"
.SH "NAME"
\fBfcoemon\fR \- The Fibre Channel over Ethernet (FCoE) administration tool
          for monitoring and processing events from the DCB daemon (\fBdcbd\fR).
.SH "SYNOPSIS"
\fBfcoemon\fR [\fB\-h\fR | \fB\-\-help\fR]
.P
\fBfcoemon\fR [\fB\-v\fR | \fB\-\-version\fR]
.P
\fBfcoemon\fR [\fB\-f\fR | \fB\-\-foreground\fR]
.P
\fBfcoemon\fR [\fB\-d\fR | \fB\-\-debug\fR]
.P
\fBfcoemon\fR [\fB\-s\fR | \fB\-\-syslog\fR]
.SH "DESCRIPTION"
The \fBfcoemon\fR command is a FCoE management tool provided by the \fBfcoe-utils\fR package.
\fBfcoemon\fR is the daemon of the \fBfcoe\fR system service.  When \fBfcoemon\fR starts, it establishes a socket
connection with the DCB daemon (\fBdcbd\fR). It then sends commands to, and receives responses
and events from \fBdcbd\fR.  \fBfcoemon\fR  will process the responses
and events and will create or destroy the FCoE interfaces as needed.
Since \fBfcoemon\fR can depend on \fBdcbd\fR, there may be settings required for \fBdcbd\fR before \fBfcoemon\fR can be started. See the \fIDCB Settings\fR section below.

The \fBfcoe\fR system may or may not depend on the DCB service. \fBfcoemon\fR will be
started by the \fBfcoe\fR service only if one of the Ethernet ports requires DCB, as specified by the \fBfcoe\fR per-interface configuration files. If no Ethernet ports require DCB then \fBfcoemon\fR will not be started and the \fBfcoe\fR service will not depend on \fBdcbd\fR.

.SH "OPTIONS"
.TP
\fB\-h | \-v | \-\-version\fR
Show the version of the \fBfcoemon\fR command.
.TP
\fB\-f | \-\-foreground\fR
Run \fBfcoemon\fR in the foreground.
.TP
\fB\-d | \-\-debug\fR
Enable debugging messages.
.TP
\fB\-s | \-\-syslog\fR
Use syslogd for logging. The default behavior is to log to stdout and stderr.
.SH "TERMINOLOGY"
.TP
\fBPFC\fR \- The DCB Priority Flow Control feature.
.TP
\fBApp:FCoE\fR \- The DCB Fibre Channel over Ethernet feature.
.TP
\fBLLINK\fR \- The DCB Logical Link TLV (or Logical Link) feature.
.TP
\fBmultiq\fR \- See Documentation/networking/multiqueue.txt of linux kernel source, v2.6.28 or higher.
.TP
\fBskbedit\fR \- See Documentation/networking/multiqueue.txt of linux kernel source v2.6.28 or higher.
.SH "INSTALLATION REQUIREMENTS"
The DCB and FCoE kernel configuration options must be enabled, these were introduced in the kernel version v2.6.29. Both the linux kernel and iproute2 must support multiq and skbedit.  The DCB package must be installed with version 0.9.4 and higher.
.SH "SUPPORTED DCB EVENTS"
In response to each supported event from \fBdcbd\fR, \fBfcoemon\fR collects the current
settings from \fBdcbd\fR to decide whether to delete and/or re-add the multiq queue discipline
and skbedit filter.
.TP
\fBFEATURE_APP\fR
If an event message is received from dcbd and if the feature code in the event message
is FEATURE_APP (5), and if the subtype field is APP_FCOE_STYPE (0), we got a mode or
configuration change event of the FCoE application.  \fBfcoemon\fR will then issue queries
to the DCB daemon to collect the current mode and configuration information.
.TP
\fBFEATURE_PFC\fR
If an event message is received from dcbd and if the feature code in the event message
is FEATURE_PFC (3), we got a mode or configuration change event of the Priority Flow
Control (PFC) feature.  The \fBfcoemon\fR will then issue queries to the DCB daemon to collect
the current mode and configuration information.
.TP
\fBFEATURE_LLINK\fR
If an event message is received from dcbd and if the feature code in the event message
is FEATURE_LLINK (6), and if the subtype field is LLINK_FCOE_STYPE (0), we got a mode
or configuration change event of the Logical Link TLV feature.  The \fBfcoemon\fR will then
issue queries to the DCB daemon to collect the current mode and configuration information.
.SH "CRITERIA OF CREATING, RESETTING  AND DESTROYING FCOE INTERFACE"
In this section the \fBdcbtool\fR is used to describe the conditions of the DCB feture status
beccause the meaning is more understandable and precise. Although you may also issue the
commands at run-time, the commands are intended only to be used for description purpose.
.TP
\fBPFC and App:FCoE\fR
DCB is configured correctly if
.RS
.PD 0
.TP 3
.BR "1)" "  The command \fBdcbtool gc ethX dcb\fR shows DCB State: on"
.TP 3
.BR "2)" "  The command \fBdcbtool gc ethX app:0\fR shows Enable:true,"
.TP 3
.BR "  " "      Advertise:true, Willing:true."
.TP 3
.BR "3)" "  The command \fBdcbtool go ethX app:0\fR shows OperMode:true."
.TP 3
.BR "4)" "  The command \fBdcbtool go ethX pfc\fR shows OperMode:true and"
.TP 3
.BR "  " "      the values of pfcup."
.TP 3
.BR "5)" "  The command \fBdcbtool go ethX app:0\fR shows appcfg. The bits"
.TP 3
.BR "  " "      set to 1 are also set to 1 in pfcup found in (4)."
.PD
.RE
.TP
\fBLogical Link TLV\fR
The Logical Link TLV feature is configured correctly if
.RS
.PD 0
.TP 3
.BR "1)" "  The command \fBdcbtool gc ethX ll:0\fR shows"
.TP 3
.BR "  " "      Enable:true, Advertise:true, Willing:true."
.TP 3
.BR "2)" "  The command \fBdcbtool go ethX ll:0\fR shows OperMode:true."
.TP 3
.BR "3)" "  The command \fBdbtool gp ethX ll:0\fR shows Link Status:up."
.PD
.RE
.TP
\fBCriteria to create FCoE interface\fR
If DCB is required at the Ethernet port, an FCoE interface may be created only if
the DCB is configured correctly. If DCB is not
required at the Ethernet port, the FCoE interface may be created.
.TP
\fBCriteria to Destroy FCoE Interface\fR
An FCoE interface will only be destroyed when the \fBfcoe\fR system service is stopped.
.TP
\fBChanging DCB Configuration, Qdisc and Filters\fR
Changing the DCB configuration, qdisc, and filter are considered to be administrative actions.
When the \fBfcoe\fR system service starts up, it sets up the default DCB configuration, qdisc, and filter
for reliable FCoE operations. Administrators may alter the configuration while the service is running.
Changing the DCB parameters may cause the \fBfcoemon\fR daemon to delete the existing multiq queue discipline,
skbedit filter and re-add; but the \fBfcoe\fR service will not touch (e.g. destroy or reset) the FCoE interface.
Changing the DCB configuration, qdisc, and filter should be avoided while I/O traffic are in progress.
.SH "FILES"
Installation of the fcoe-utils management tools include the following files:
.TP
\fI/etc/fcoe/config\fR
This is the primary configuration file for the \fBfcoe\fR system service. The default options in this file are: \fBDEBUG="no"\fR and \fBUSE_SYSLOG="yes"\fR. The former is used to enable
debugging messages from the \fBfcoe\fR service script and \fBfcoemon\fR. The latter is
to indicate if the log messages are to be output to the system log.  Any changes to this file will require a restart of the \fBfcoe\fR service.
.TP
\fI/etc/fcoe/cfg-<ifname>\fR
This file will be read by the \fI/etc/init.d/fcoe\fR script and the \fBfcoemon\fR daemon.  The default options in this file are:
\fBFCOE_ENABLE="no"\fR and \fBDCB_REQUIRED="yes"\fR.  The former is used to enable/disable the FCoE service at the ethX port. The latter is to indicate if the DCB service
is required (select yes) or not required (select no) at the ethX port. If the former is set to no, the
latter is ignored. The selection of the settings should match the settings of the FCoE switch port connected
to the local Ethernet ethX port. Use an editor to set the desired \fByes/no\fR
values for the \fBethX\fR interfaces.
.TP
\fI/etc/init.d/fcoe\fR
This is the \fBfcoe\fR system service shell script. This script is invoked by the \fBinit\fR process
or by the \fBservice\fR command.
.TP
\fI/sbin/fcoemon\fR
This is the \fBfcoemon\fR daemon only invoked by the \fBfcoe\fR system service script.
.TP
\fI/sbin/fcoeadm\fR
This is the program used by the \fBfcoe\fR system service to create or destroy FCoE interfaces.
.SH "REPORTING BUGS"
If you have identified a defect please file a bug with your distribution or engage the
development mailing list at <http://www.Open\-FCoE.org>.
.SH "SUPPORT"
Open\-FCoE is maintained at <http://www.Open\-FCoE.org>. There are resources
available for both developers and users at that site.


