.TH FCOEADM 8 "August 21, 2008" "Open-FCoE Applications" "Open-FCoE Tools"
.SH "NAME"
fcoeadm \- The Fibre Channel over Ethernet (FCoE) administration tool
.SH "SYNOPSIS"
fcoeadm [[\fB\-c\fR|\fB\-\-create\fR] | [\fB\-d\fR|\fB\-\-destroy\fR] | [\fB\-r\fR|\fB\-\-reset\fR] | [\fB\-q\fR|\fB\-\-query\fR]] \fI<ifname>\fR]
.P
fcoeadm [\fB\-h\fR|\fB\-\-help\fR]
.SH "DESCRIPTION"
Creates, destroys, resets, or queries an FCoE instance on a given network interface.
.SH "OPTIONS"
.TP
\fB\-c\fR, \fB\-\-create\fR \fI<ifname>\fR
Creates an FCoE instance based on the given \fI<ifname>\fR. It first checks the 
existence of /sys/module/fcoe/ to verify that the fcoe module is loaded. Then 
the \fI<ifname>\fR is written to /sys/module/fcoe/create.
.TP
\fB\-d\fR, \fB\-\-destroy\fR \fI<ifname>\fR
Destroys an FCoE instance based on the given \fI<ifname>\fR. It first checks the
existence of /sys/module/fcoe/ to verify that fcoe module is loaded. Then
the \fI<ifname>\fR is written to /sys/module/fcoe/destroy. 
.TP
\fB\-r\fR, \fB\-\-reset\fR \fI<ifname>\fR
Resets the fc_host associated with the FCoE interface given by \fI<ifname>\fR.
.TP
\fB\-q\fR, \fB\-\-query\fR \fI<ifname>\fR
Queries basic FCoE information for the given \fI<ifname>\fR. It looks for the
corresponding fc_host under /sys/class/fc_host/. If a fc_host is found
for the \fI<ifname>\fR, basic information such as port ID, worldwide port name,
worldwide node name, and fabric name will be displayed.
.TP
\fB\-h\fR, \fB\-\-help\fR \fI<ifname>\fR
Displays this help information.
.TP 
\fI<ifname>\fR
The network interface name, such as eth0, eth1, etc.
.SH "EXAMPLES"
Creates an FCoE instance on eth2
.IP 
$ fcoeadm --create eth2
.P
Destroys the FCoE instance on eth2
.IP 
$ fcoeadm --destroy eth2
.P
Resets the FCoE instance on eth2
.IP 
$ fcoeadm --reset eth2
.P
Queries FCoE information on eth2
.IP 
$ fcoeadm --query eth2
.SH "REPORTING BUGS"
If you have identified a
defect please either file a bug or engage the development mailing list at
<http://www.Open-FCoE.org>.
.SH "SUPPORT"
Open-FCoE is maintained at <http://www.Open-FCoE.org>. There are resources
available for both developers and users at that site.


