'\" t
.\"     Title: fipvlan
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 10/06/2011
.\"    Manual: Open-FCoE Tools
.\"    Source: Open-FCoE
.\"  Language: English
.\"
.TH "FIPVLAN" "8" "10/06/2011" "Open\-FCoE" "Open\-FCoE Tools"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
fipvlan \- Fibre Channel over Ethernet VLAN Discovery
.SH "SYNOPSIS"
.sp
\fBfipvlan\fR [\-c|\-\-create] [\-s|\-\-start] \fIinterfaces\fR
.sp
\fBfipvlan\fR \-a|\-\-auto [\-c|\-\-create] [\-d|\-\-debug]
[\-s|\-\-start] [\-l|\-\-link-retry <num>]
.sp
\fBfipvlan\fR \-h|\-\-help
.sp
\fBfipvlan\fR \-v|\-\-version
.SH "DESCRIPTION"
.sp
The \fBfipvlan\fR command performs Fibre Channel over Ethernet (FCoE)
Initialization Protocol (FIP) VLAN Discovery over Ethernet
interfaces\&. \fBfipvlan\fR can be used as a diagnostic tool to
determine which VLANs have FCoE services available on a network, prior
to configuring VLAN interfaces and the \fIOpen\-FCoE\fR
initiator\&. \fBfipvlan\fR can also be used to create VLAN interfaces
as they are discovered, and to start the \fIOpen\-FCoE\fR
initiator\&. The \fB\-\-create\fR and \fB\-\-start\fR options are
primarily intended to be used as part of an \fIOpen\-FCoE\fR boot
solution\&. FCoE instances started in this way cannot be destroyed or
reset by fcoeadm\&.
.sp
\fBfipvlan\fR takes a list of network interface names to run the VLAN
discovery protocol over, or the \fB\-\-auto\fR option to use all
available Ethernet interfaces\&.
.sp
\fBfipvlan\fR will enable any interface which is found to be not
enabled by the time the program runs. If no response is received
on that interface it will be shutdown again when fipvlan terminates.
.SH "OPTIONS"
.PP
\fB\-a\fR, \fB\-\-auto\fR
.RS 4
Use all Ethernet interfaces currently available
.RE
.PP
\fB\-c\fR, \fB\-\-create\fR
.RS 4
Create network interfaces for discovered FCoE VLANs\&. If a VLAN device already exists for a discovered VLAN, a new VLAN device will not be created\&.
.RE
.PP
\fB\-d\fR, \fB\-\-debug\fR
.RS 4
Enable debugging output
.RE
.PP
\fB\-s\fR, \fB\-\-start\fR
.RS 4
Start the
\fIOpen\-FCoE\fR
initiator on discovered FCoE VLANs
.RE
.PP
\fB\-f\fR, \fB\-\-suffix \fI<suffix string>\fR
.RS 4
Append the specified string \fI<suffix string>\fR to VLAN interface names.
.RE
.PP
\fB\-l\fR, \fB\-\-link-retry \fI<number of retries>\fR
.RS 4
Retry check for link up up to \fI<number of retries>\fR times. The
link state is retried every 500 ms. The default is 20.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Display a help message with basic usage instructions
.RE
.PP
\fB\-v\fR, \fB\-\-version\fR
.RS 4
Display the
\fBfipvlan\fR
version string
.RE
.SH "VLAN NAMING CONVENTIONS"
.sp
The default VLAN device name is \fIdev\fR\&.\fIvlan\fR; where
\fIdev\fR is the name of the Ethernet parent device and \fIvlan\fR is
the discovered VLAN ID number\&. An optional suffix can be appended to
this with \fI-f\fR commandline option.
.SH "EXAMPLES"
.sp
Display all discoverable VLANs with FCoE services
.sp
.if n \{\
.RS 4
.\}
.nf
fipvlan \-\-auto
.fi
.if n \{\
.RE
.\}
.sp
Discover FCoE VLANs on interface eth2, create VLAN devices and start the \fIOpen\-FCoE\fR initiator
.sp
.if n \{\
.RS 4
.\}
.nf
fipvlan \-\-create \-\-start eth2
.fi
.if n \{\
.RE
.\}
.sp
In this example if FCoE services were available on VLAN 101 of network interface eth2, then a VLAN interface eth2\&.101\-fcoe would be created and used as the parent device for the initiator\&.
.SH "SEE ALSO"
.sp
\fBfcoeadm\fR(8) \fBfcoemon\fR(8)
.SH "SUPPORT"
.sp
\fBfipvlan\fR is part of the \fIfcoe\-utils\fR package, maintained through the \fIOpen\-FCoE\fR project\&. Resources for both developers and users can be found at the \fIOpen\-FCoE\fR website http://open\-fcoe\&.org/
